### ISSUE TITLE
Not exactly an issue but:

### ISSUE THREAD

**Issue by capjay45** [RestoreMonarchyPlugins/Pickpocket#1]
How do I give people permission? I turned on "use permissions" but what command do I put in the permission.config.xml file? thanks!

**Comment by RestoreMonarchy** [comment]
Oh I should have mentioned it in README 

The permission to bypass pickpocket is `bypass.pickpocket`

**Comment by capjay45** [comment]
> Oh I should have mentioned it in README
> 
> The permission to bypass pickpocket is `bypass.pickpocket`

OH ok thanks man!

**Comment by capjay45** [comment]
> Oh I should have mentioned it in README
> 
> The permission to bypass pickpocket is `bypass.pickpocket`

I just tested it and It doesn't work. I can't pickpocket anyone. I gave the mafia bypass.pickpocket me and my friend cant pickpocket. have I done something wrong?

**Comment by RestoreMonarchy** [comment]
if you give someone bypass permission he cannot be robbed
